### ISSUE TITLE
Some recent changes are missing from master

### ISSUE THREAD

**Issue by jptomoya** [ptr-yudai/ptrlib#30]
It seems current master branch ([6409a5b](https://github.com/ptr-yudai/ptrlib/tree/6409a5bc6a130482646d7e0bf08cbfc328723bf7)) does not reflect the commit [f27c17a](https://github.com/ptr-yudai/ptrlib/commit/f27c17a4110a2afc1c37ee9227528c0fd09ef15a) which merged #29. As a result, some recent changes are missing from master branch, including the changes from #27 and #29.

The following commands should fix the issue. However, please proceed only if you fully understand the implications:

```
git fetch origin f27c17a4110a2afc1c37ee9227528c0fd09ef15a
git switch master
git reset --hard f27c17a4110a2afc1c37ee9227528c0fd09ef15a
git push -f origin master
```

**Comment by ptr-yudai** [comment]
It's intended :P
